# Generated by Django 4.2.5 on 2025-12-15 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_api', '0002_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='如果是对回复的回复，则指向父回复；如果是对帖子的直接回复，则为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum_api.forumreply', verbose_name='父回复'),
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_records', to='forum_api.forumreply', verbose_name='回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '回复点赞',
                'verbose_name_plural': '回复点赞',
                'ordering': ['-created_at'],
                'unique_together': {('reply', 'user')},
            },
        ),
    ]
