# Generated by Django 4.2.5 on 2025-12-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0004_notification_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_api.forumreply', verbose_name='相关回复'),
        ),
    ]
