# Generated by Django 4.2.5 on 2025-12-18 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=200, unique=True, verbose_name='比赛ID')),
                ('date', models.DateField(verbose_name='比赛日期')),
                ('day', models.IntegerField(verbose_name='日')),
                ('month', models.IntegerField(verbose_name='月')),
                ('year', models.IntegerField(verbose_name='年')),
                ('day_week', models.CharField(blank=True, max_length=20, verbose_name='星期')),
                ('status', models.CharField(choices=[('finished', '已完成'), ('upcoming', '即将开始')], default='upcoming', max_length=20, verbose_name='状态')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'ordering': ['-date', '-year', '-month', '-day'],
            },
        ),
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(help_text='如：第1回戦', max_length=50, verbose_name='回合名称')),
                ('round_number', models.IntegerField(verbose_name='回合编号')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='mleague.match', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛回合',
                'verbose_name_plural': '比赛回合',
                'ordering': ['match', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='选手名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '选手',
                'verbose_name_plural': '选手',
                'ordering': ['team', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='队伍ID')),
                ('team_name', models.CharField(max_length=100, unique=True, verbose_name='队伍名称')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='排名')),
                ('team_name', models.CharField(max_length=100, verbose_name='战队名称')),
                ('score', models.CharField(max_length=50, verbose_name='积分')),
                ('season', models.CharField(default='2025赛季', max_length=50, verbose_name='赛季')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '战队排名',
                'verbose_name_plural': '战队排名',
                'ordering': ['rank', 'season'],
                'indexes': [models.Index(fields=['season', 'rank'], name='mleague_tea_season_9bcac7_idx'), models.Index(fields=['team_name'], name='mleague_tea_team_na_4f8c27_idx')],
                'unique_together': {('rank', 'season')},
            },
        ),
        migrations.CreateModel(
            name='TeamPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2025赛季', max_length=50, verbose_name='赛季')),
                ('points_type', models.CharField(choices=[('total_points', '综合积分'), ('regular_points', 'Regular积分'), ('postseason_points', 'Post-season积分'), ('semifinal_points', 'Semifinal积分'), ('final_points', 'Final积分')], max_length=50, verbose_name='积分类型')),
                ('points_data', models.JSONField(default=dict, help_text='存储从表格中获取的所有列数据', verbose_name='积分数据')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='mleague.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '队伍积分',
                'verbose_name_plural': '队伍积分',
                'ordering': ['season', 'points_type', 'team'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2025赛季', max_length=50, verbose_name='赛季')),
                ('matches', models.IntegerField(blank=True, null=True, verbose_name='试合数')),
                ('total_games', models.IntegerField(blank=True, null=True, verbose_name='总局数')),
                ('points', models.FloatField(blank=True, null=True, verbose_name='ポイント')),
                ('average_rank', models.FloatField(blank=True, null=True, verbose_name='平着')),
                ('first_place', models.IntegerField(blank=True, null=True, verbose_name='1位')),
                ('second_place', models.IntegerField(blank=True, null=True, verbose_name='2位')),
                ('third_place', models.IntegerField(blank=True, null=True, verbose_name='3位')),
                ('fourth_place', models.IntegerField(blank=True, null=True, verbose_name='4位')),
                ('top_rate', models.FloatField(blank=True, null=True, verbose_name='トップ率')),
                ('renchan_rate', models.FloatField(blank=True, null=True, verbose_name='連対率')),
                ('last_avoidance_rate', models.FloatField(blank=True, null=True, verbose_name='ラス回避率')),
                ('best_score', models.IntegerField(blank=True, null=True, verbose_name='ベストスコア')),
                ('average_score', models.FloatField(blank=True, null=True, verbose_name='平均打点')),
                ('furo_rate', models.FloatField(blank=True, null=True, verbose_name='副露率')),
                ('riichi_rate', models.FloatField(blank=True, null=True, verbose_name='リーチ率')),
                ('agari_rate', models.FloatField(blank=True, null=True, verbose_name='アガリ率')),
                ('houjuu_rate', models.FloatField(blank=True, null=True, verbose_name='放銃率')),
                ('houjuu_average_score', models.FloatField(blank=True, null=True, verbose_name='放銃平均打点')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='mleague.player', verbose_name='选手')),
            ],
            options={
                'verbose_name': '选手统计',
                'verbose_name_plural': '选手统计',
                'ordering': ['season', 'player__team', 'player__player_name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mleague.team', verbose_name='所属队伍'),
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='队伍在比赛中的显示顺序', verbose_name='顺序')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='mleague.match', verbose_name='比赛')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='mleague.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '比赛队伍',
                'verbose_name_plural': '比赛队伍',
                'ordering': ['match', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchRoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('score_text', models.CharField(blank=True, help_text='如：54.9pt', max_length=50, verbose_name='得分文本')),
                ('player_avatar_url', models.URLField(blank=True, null=True, verbose_name='选手头像URL')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='mleague.player', verbose_name='选手')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mleague.matchround', verbose_name='回合')),
            ],
            options={
                'verbose_name': '回合结果',
                'verbose_name_plural': '回合结果',
                'ordering': ['round', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date'], name='mleague_mat_date_17e9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['year', 'month'], name='mleague_mat_year_5e9fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='mleague_mat_status_efd649_idx'),
        ),
        migrations.AddIndex(
            model_name='teampoints',
            index=models.Index(fields=['season', 'points_type'], name='mleague_tea_season_952ef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teampoints',
            unique_together={('team', 'season', 'points_type')},
        ),
        migrations.AddIndex(
            model_name='playerstats',
            index=models.Index(fields=['season', 'player'], name='mleague_pla_season_0c4ee2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('player_name', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='matchteam',
            unique_together={('match', 'team', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='matchroundresult',
            unique_together={('round', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='matchround',
            unique_together={('match', 'round_number')},
        ),
    ]
