# Generated by Django 4.2.5 on 2025-12-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_type', models.CharField(choices=[('total_points', '综合积分'), ('regular_points', 'Regular积分'), ('postseason_points', 'Post-season积分'), ('semifinal_points', 'Semifinal积分'), ('final_points', 'Final积分')], db_index=True, max_length=50, verbose_name='积分类型')),
                ('team_data', models.JSONField(default=list, help_text='各队伍的积分数据列表', verbose_name='队伍积分数据')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分数据',
                'verbose_name_plural': '积分数据',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='队伍ID')),
                ('team_name', models.CharField(db_index=True, max_length=100, verbose_name='队伍名称')),
                ('season', models.CharField(db_index=True, default='2025赛季', max_length=50, verbose_name='赛季')),
                ('players', models.JSONField(default=list, help_text='选手统计信息列表', verbose_name='选手数据')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '队伍选手统计',
                'verbose_name_plural': '队伍选手统计',
                'ordering': ['season', 'team_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='matchround',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='match',
        ),
        migrations.AlterUniqueTogether(
            name='matchroundresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matchroundresult',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchroundresult',
            name='round',
        ),
        migrations.AlterUniqueTogether(
            name='matchteam',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matchteam',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchteam',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player',
        ),
        migrations.AlterUniqueTogether(
            name='teampoints',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teampoints',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '比赛', 'verbose_name_plural': '比赛'},
        ),
        migrations.AlterModelOptions(
            name='teamranking',
            options={'ordering': ['season', 'rank'], 'verbose_name': '队伍排名', 'verbose_name_plural': '队伍排名'},
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='mleague_mat_status_efd649_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamranking',
            name='mleague_tea_team_na_4f8c27_idx',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.JSONField(blank=True, help_text='比赛详细结果', null=True, verbose_name='比赛结果'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.JSONField(default=list, help_text='队伍信息列表', verbose_name='参赛队伍'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(db_index=True, verbose_name='比赛日期'),
        ),
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='日期（日）'),
        ),
        migrations.AlterField(
            model_name='match',
            name='day_week',
            field=models.CharField(blank=True, max_length=10, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='match',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='比赛ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', '即将开始'), ('finished', '已完成')], db_index=True, default='upcoming', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='match',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='season',
            field=models.CharField(db_index=True, default='2025赛季', max_length=50, verbose_name='赛季'),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='team_name',
            field=models.CharField(max_length=100, verbose_name='队伍名称'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'date'], name='mleague_mat_status_49b535_idx'),
        ),
        migrations.DeleteModel(
            name='MatchRound',
        ),
        migrations.DeleteModel(
            name='MatchRoundResult',
        ),
        migrations.DeleteModel(
            name='MatchTeam',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamPoints',
        ),
        migrations.AddIndex(
            model_name='teamplayerstats',
            index=models.Index(fields=['season', 'team_name'], name='mleague_tea_season_0ab279_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamplayerstats',
            unique_together={('team_name', 'season')},
        ),
        migrations.AddIndex(
            model_name='pointsdata',
            index=models.Index(fields=['points_type', '-last_updated'], name='mleague_poi_points__888adc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointsdata',
            unique_together={('points_type',)},
        ),
    ]
