[pytest]
# 将 'your_project_name' 替换为你实际的 Django 项目文件夹名称
DJANGO_SETTINGS_MODULE = backend.settings

# 告诉 pytest 去哪里找测试文件（匹配所有以 test_ 开头或以 _test 结尾的文件）
python_files = test.py tests.py test_*.py *_tests.py