# Generated by Django 4.2.5 on 2025-12-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_likes',
            field=models.IntegerField(default=0, verbose_name='获赞数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_posts_count',
            field=models.IntegerField(default=0, verbose_name='发帖数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_replies_count',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='已验证'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_practice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后练习时间'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='practice_accuracy',
            field=models.FloatField(default=0.0, verbose_name='平均正确率'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='practice_completed',
            field=models.IntegerField(default=0, verbose_name='完成练习数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='practice_rank',
            field=models.CharField(default='未评级', max_length=50, verbose_name='段位'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_practice_time',
            field=models.IntegerField(default=0, verbose_name='总练习时长(分钟)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否员工'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='是否超级用户'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'ordering': ['-earned_at'],
            },
        ),
    ]
