# Generated by Django 4.2.5 on 2025-12-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forum_likes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forum_posts_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forum_replies_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_practice_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='practice_accuracy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='practice_completed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='practice_rank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_practice_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
