# Generated by Django 4.2.5 on 2025-12-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_customuser_options_remove_customuser_avatar_and_more'),
    ]

    operations = [
    ]
