# Generated by Django 4.2.5 on 2025-12-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_customuser_first_name_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, default='https://placehold.co/100x100/6366f1/ffffff?text=User', help_text='用户头像图片链接', max_length=500, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='单位：%', max_digits=5, verbose_name='平均正确率'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_exercises',
            field=models.IntegerField(default=0, help_text='已完成的练习题数量', verbose_name='已完成练习'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_rank',
            field=models.CharField(default='一段', help_text='如：一段、二段、三段、四段等', max_length=50, verbose_name='当前段位'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(blank=True, help_text='用户加入平台的日期', null=True, verbose_name='加入日期'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes_received',
            field=models.IntegerField(default=0, help_text='在论坛获得的点赞数量', verbose_name='获得点赞数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='replies_count',
            field=models.IntegerField(default=0, help_text='在论坛的回复数量', verbose_name='回复数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='topics_published',
            field=models.IntegerField(default=0, help_text='在论坛发布的主题数量', verbose_name='发布主题数'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否员工'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='是否超级用户'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='用户名'),
        ),
    ]
