# Generated by Django 4.2.5 on 2025-12-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, default='https://placehold.co/100x100/6366f1/ffffff?text=User', help_text='用户头像图片链接或base64数据', verbose_name='头像'),
        ),
    ]
