# Generated by Django 4.2.5 on 2025-12-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0007_alter_avatar_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', '超级管理员'), ('news_editor', '新闻编辑者'), ('practice_editor', '练习编辑者'), ('moderator', '版主'), ('forum_moderator', '论坛版主'), ('content_manager', '内容管理员')], help_text='管理员角色的唯一标识', max_length=50, unique=True, verbose_name='角色名称')),
                ('display_name', models.CharField(help_text='在界面中显示的角色名称', max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, help_text='角色的详细描述和职责', verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用该角色', verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='该角色关联的用户组', to='auth.group', verbose_name='用户组')),
                ('permissions', models.ManyToManyField(blank=True, help_text='该角色拥有的具体权限', to='auth.permission', verbose_name='权限列表')),
            ],
            options={
                'verbose_name': '管理员角色',
                'verbose_name_plural': '管理员角色',
                'db_table': 'admin_roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='用户的管理员角色（如果适用）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.adminrole', verbose_name='管理员角色'),
        ),
    ]
