# Generated by Django 4.2.5 on 2025-12-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, help_text='如果设置，前端将显示此标签而不是分类名称', max_length=50, verbose_name='显示标签'),
        ),
    ]
