# Generated by Django 4.2.5 on 2025-12-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_majsoul_news'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='majsoulnews',
            new_name='news_api_ma_publish_be9d1d_idx',
            old_name='majsoul_news_published_at_idx',
        ),
        migrations.RenameIndex(
            model_name='majsoulnews',
            new_name='news_api_ma_is_acti_795e87_idx',
            old_name='majsoul_news_active_published_at_idx',
        ),
        migrations.RenameIndex(
            model_name='majsoulnews',
            new_name='news_api_ma_categor_afc9e8_idx',
            old_name='majsoul_news_category_published_at_idx',
        ),
        migrations.AlterField(
            model_name='majsoulnews',
            name='link',
            field=models.URLField(db_index=True, unique=True, verbose_name='原文链接'),
        ),
    ]
