# Generated by Django 4.2.5 on 2025-12-23 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naze300Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(help_text='题目编号 (1-300)', unique=True)),
                ('title', models.CharField(help_text='题目标题', max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('basic', '基础'), ('intermediate', '进阶'), ('advanced', '高级')], default='basic', max_length=20)),
                ('hand_tiles', models.CharField(help_text='手牌字符串表示（14张牌）', max_length=100)),
                ('discard_options', models.JSONField(help_text='可选切牌列表')),
                ('correct_discard', models.CharField(help_text='正确切牌', max_length=10)),
                ('correct_reason', models.TextField(help_text='正确切牌理由')),
                ('additional_notes', models.TextField(blank=True, help_text='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='总尝试次数')),
                ('correct_attempts', models.PositiveIntegerField(default=0, help_text='正确次数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '何切300问题目',
                'verbose_name_plural': '何切300问题目',
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='UserNazeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='not_started', max_length=15)),
                ('is_correct', models.BooleanField(help_text='是否答对', null=True)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_api.naze300question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户何切进度',
                'verbose_name_plural': '用户何切进度',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
