# Generated by Django 4.2.5 on 2025-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naze300question',
            name='dora_indicators',
            field=models.CharField(blank=True, help_text='宝牌指示牌', max_length=50),
        ),
        migrations.AddField(
            model_name='naze300question',
            name='player_wind',
            field=models.CharField(default='东', help_text='自风', max_length=10),
        ),
        migrations.AddField(
            model_name='naze300question',
            name='round_wind',
            field=models.CharField(default='东', help_text='场风', max_length=10),
        ),
        migrations.AddField(
            model_name='naze300question',
            name='tsumi_number',
            field=models.PositiveIntegerField(default=0, help_text='巡目/本场数'),
        ),
        migrations.AddField(
            model_name='naze300question',
            name='ura_dora_indicators',
            field=models.CharField(blank=True, help_text='里宝牌指示牌', max_length=50),
        ),
    ]
