# Generated by Django 4.2.5 on 2025-12-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_api', '0002_naze300question_dora_indicators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajsoulNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('cover_image', models.URLField(blank=True, verbose_name='封面图URL')),
                ('category', models.CharField(choices=[('update', '游戏更新'), ('event', '活动公告'), ('maintenance', '维护通知'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_url', models.URLField(blank=True, verbose_name='来源URL')),
                ('source_id', models.CharField(blank=True, max_length=100, verbose_name='来源ID')),
            ],
            options={
                'verbose_name': '雀魂游戏信息',
                'verbose_name_plural': '雀魂游戏信息',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
