# Generated by Django 4.2.5 on 2025-12-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_api', '0003_majsoulnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MajsoulNews',
        ),
    ]
